import 'dart:ffi';

///Hive Types
const int HIVE_TYPE_ID_MOVIE_VO=1;
const int HIVE_TYPE_ID_COLLECTION_VO=2;
const int HIVE_TYPE_ID_GENRE_VO=3;
const int HIVE_TYPE_ID_PRODUCTION_COMPANY_VO=4;
const int HIVE_TYPE_ID_PRODUCTION_COUNTRY_VO=5;
const int HIVE_TYPE_ID_SPOKEN_LANGUAGE_VO=6;
const int HIVE_TYPE_ID_CREDIT_VO=7;
const int HIVE_TYPE_ID_ACTOR_VO=8;
const int HIVE_TYPE_ID_DATE_VO=9;
const int HIVE_TYPE_ID_BANNER_VO=10;
const int HIVE_TYPE_ID_USER_VO=11;
const int HIVE_TYPE_ID_CITY_VO=12;
const int HIVE_TYPE_ID_CONFIG_VO=13;
const int HIVE_TYPE_ID_CINEMA_TIME_SLOTS_STATUS_VO=14;
const int HIVE_TYPE_ID_CINEMA_VO=15;
const int HIVE_TYPE_ID_FACILITY_VO=16;
const int HIVE_TYPE_ID_CINEMA_AND_SHOW_TIME_SLOTS_VO=17;
const int HIVE_TYPE_ID_TIME_SLOT_VO=18;
const int HIVE_TYPE_ID_SEAT_VO=19;
const int HIVE_TYPE_ID_SNACK_CATEGORY_VO=20;
const int HIVE_TYPE_ID_SNACK_VO=21;
const int HIVE_TYPE_ID_PAYMENT_VO=22;
const int HIVE_TYPE_ID_CHECK_OUT_VO=23;
const int HIVE_TYPE_ID_CINEMA_AND_SHOW_TIME_BY_DATE_VO=24;

///Box Names
const String BOX_NAME_MOVIE_VO="BOX_NAME_MOVIE_VO";
const String BOX_NAME_CREDIT_VO="BOX_NAME_CREDIT_VO";
const String BOX_NAME_BANNER_VO="BOX_NAME_BANNER_VO";
const String BOX_NAME_USER_DATA_VO="BOX_NAME_USER_DATA_VO";
const String BOX_NAME_CITY_VO="BOX_NAME_CITY_VO";
const String BOX_NAME_CONFIG_VO="BO_NAME_CONFIG_VO";
const String BOX_NAME_CINEMA_TIME_SLOTS_STATUS_VO="BOX_NAME_CINEMA_TIME_SLOTS_STATUS_VO";
const String BOX_NAME_CINEMA_VO="BOX_NAME_CINEMA_VO";
const String BOX_NAME_FACILITY_VO="BOX_NAME_FACILITY_VO";
const String BOX_NAME_CINEMA_AND_SHOW_TIME_SLOTS_VO="BOX_NAME_CINEMA_AND_SHOW_TIME_SLOTS_VO";
const String BOX_NAME_TIME_SLOT_VO="BOX_NAME_TIME_SLOT_VO";
const String BOX_NAME_SEAT_VO="BOX_NAME_SEAT_VO";
const String BOX_NAME_SNACK_CATEGORY_VO="BOX_NAME_SNACK_CATEGORY_VO";
const String BOX_NAME_SNACK_VO="BOX_NAME_SNACK_VO";
const String BOX_NAME_PAYMENT_VO="BOX_NAME_PAYMENT_VO";
const String BOX_NAME_CHECK_OUT_VO="BOX_NAME_CHECK_OUT_VO";
const String BOX_NAME_CINEMA_AND_SHOW_TIME_BY_DATE_VO="BOX_NAME_CINEMA_AND_SHOW_TIME_BY_DATE_VO";
